### ISSUE TITLE
Reduce city growth rate

### ISSUE THREAD

**Issue by mayant15** [Terasology/MetalRenegades#41]
We may have to reduce city growth rate for more even gameplay. To do that, we'll have to first expose the `counter` in the `SettlementEntityManager` (located in Terasology/DynamicCities [here](https://github.com/Terasology/DynamicCities/blob/ed7b1e80290ef8dbf23dd45f002cdb1f41afbb41/src/main/java/org/terasology/dynamicCities/settlements/SettlementEntityManager.java#L134)) to other modules. We may use a `setCityGrowthRate` function in the `SettlementEntityManager` which is just a setter for `counter` and expose this function to MetalRenegades.

**Comment by agent-q1** [comment]
I think this issue should be updated with _cyclesleft_ instead of _counter_. I'd love to have a go at this anyways. Please correct me if my approach is wrong.
Also I noticed that the number 2 is hardcoded in a number of places. I might consider adding a new private variable called NumberOfCyclesOnReset

**Comment by skaldarnar** [comment]
Honestly, this looks like the wrong approach to address this. DynamicCities introduces _Cultures_ to be able to allow for cities of different styles, each with their own properties. In particular, the [`CultureComponent`](https://github.com/Terasology/DynamicCities/blob/master/src/main/java/org/terasology/dynamicCities/population/CultureComponent.java) allows to set a `growthRate`.

MetalRenegades introduces a [`default` culture](https://github.com/Terasology/MetalRenegades/blob/master/assets/prefabs/cultures/default.prefab) with a growth rate of 500. I would assume that this should allow to reduce the growth rate.

From a gameplay perspective, it may even be possible to set the growth to 0 at the beginning, and only increase it after the player fulfilled some tasks or purchased some items...

**Comment by AndyTechGuy** [comment]
City growth rate has been adjusted in #67
